#[path = "../first_collation_string_slice.rs"]
pub mod first_collation_string_slice;
#[path = "../first_decimal128_slice.rs"]
pub mod first_decimal128_slice;
#[path = "../first_exchange_slice.rs"]
pub mod first_exchange_slice;
#[path = "../first_expression_slice.rs"]
pub mod first_expression_slice;
#[path = "../first_filter_is_not_null_slice.rs"]
pub mod first_filter_is_not_null_slice;
#[path = "../first_float64_ordering_slice.rs"]
pub mod first_float64_ordering_slice;
#[path = "../first_json_slice.rs"]
pub mod first_json_slice;
#[path = "../first_map_slice.rs"]
pub mod first_map_slice;
#[path = "../first_signed_widening_add_int64_slice.rs"]
pub mod first_signed_widening_add_int64_slice;
#[path = "../first_struct_slice.rs"]
pub mod first_struct_slice;
#[path = "../first_temporal_date32_slice.rs"]
pub mod first_temporal_date32_slice;
#[path = "../first_temporal_timestamp_tz_slice.rs"]
pub mod first_temporal_timestamp_tz_slice;
#[path = "../first_union_slice.rs"]
pub mod first_union_slice;
#[path = "../first_unsigned_arithmetic_slice.rs"]
pub mod first_unsigned_arithmetic_slice;
